<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/02 13:50:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=iic2143',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
