<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/08/22 11:16:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=iic2143',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
